//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parker.Sandbox.AMSConnect {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CityConnectSignupViewModel", Namespace="http://schemas.datacontract.org/2004/07/MASC.AMS.ClienteWeb.services.ViewModels")]
    [System.SerializableAttribute()]
    public partial class CityConnectSignupViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Parker.Sandbox.AMSConnect.Name NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Parker.Sandbox.AMSConnect.Name Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Name", Namespace="http://schemas.datacontract.org/2004/07/MASC.AMS.ClienteWeb.services.ViewModels")]
    [System.SerializableAttribute()]
    public partial class Name : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string First {
            get {
                return this.FirstField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstField, value) != true)) {
                    this.FirstField = value;
                    this.RaisePropertyChanged("First");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Last {
            get {
                return this.LastField;
            }
            set {
                if ((object.ReferenceEquals(this.LastField, value) != true)) {
                    this.LastField = value;
                    this.RaisePropertyChanged("Last");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IndividualViewModel", Namespace="http://schemas.datacontract.org/2004/07/MASC.AMS.ClienteWeb.services.ViewModels")]
    [System.SerializableAttribute()]
    public partial class IndividualViewModel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailAddresField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PhoneNumberField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PrefixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuffixField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WebLoginField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailAddres {
            get {
                return this.EmailAddresField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailAddresField, value) != true)) {
                    this.EmailAddresField = value;
                    this.RaisePropertyChanged("EmailAddres");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName {
            get {
                return this.FirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstNameField, value) != true)) {
                    this.FirstNameField = value;
                    this.RaisePropertyChanged("FirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PhoneNumber {
            get {
                return this.PhoneNumberField;
            }
            set {
                if ((object.ReferenceEquals(this.PhoneNumberField, value) != true)) {
                    this.PhoneNumberField = value;
                    this.RaisePropertyChanged("PhoneNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefix {
            get {
                return this.PrefixField;
            }
            set {
                if ((object.ReferenceEquals(this.PrefixField, value) != true)) {
                    this.PrefixField = value;
                    this.RaisePropertyChanged("Prefix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Suffix {
            get {
                return this.SuffixField;
            }
            set {
                if ((object.ReferenceEquals(this.SuffixField, value) != true)) {
                    this.SuffixField = value;
                    this.RaisePropertyChanged("Suffix");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title {
            get {
                return this.TitleField;
            }
            set {
                if ((object.ReferenceEquals(this.TitleField, value) != true)) {
                    this.TitleField = value;
                    this.RaisePropertyChanged("Title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WebLogin {
            get {
                return this.WebLoginField;
            }
            set {
                if ((object.ReferenceEquals(this.WebLoginField, value) != true)) {
                    this.WebLoginField = value;
                    this.RaisePropertyChanged("WebLogin");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AMSConnect.IMASCAMSConnectService")]
    public interface IMASCAMSConnectService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMASCAMSConnectService/CityConnectSignUp", ReplyAction="http://tempuri.org/IMASCAMSConnectService/CityConnectSignUpResponse")]
        void CityConnectSignUp(Parker.Sandbox.AMSConnect.CityConnectSignupViewModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMASCAMSConnectService/CityConnectSignUp", ReplyAction="http://tempuri.org/IMASCAMSConnectService/CityConnectSignUpResponse")]
        System.Threading.Tasks.Task CityConnectSignUpAsync(Parker.Sandbox.AMSConnect.CityConnectSignupViewModel model);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMASCAMSConnectService/CreateIndividual", ReplyAction="http://tempuri.org/IMASCAMSConnectService/CreateIndividualResponse")]
        Parker.Sandbox.AMSConnect.IndividualViewModel CreateIndividual();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMASCAMSConnectService/CreateIndividual", ReplyAction="http://tempuri.org/IMASCAMSConnectService/CreateIndividualResponse")]
        System.Threading.Tasks.Task<Parker.Sandbox.AMSConnect.IndividualViewModel> CreateIndividualAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMASCAMSConnectService/Search", ReplyAction="http://tempuri.org/IMASCAMSConnectService/SearchResponse")]
        Parker.Sandbox.AMSConnect.IndividualViewModel[] Search();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMASCAMSConnectService/Search", ReplyAction="http://tempuri.org/IMASCAMSConnectService/SearchResponse")]
        System.Threading.Tasks.Task<Parker.Sandbox.AMSConnect.IndividualViewModel[]> SearchAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMASCAMSConnectServiceChannel : Parker.Sandbox.AMSConnect.IMASCAMSConnectService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MASCAMSConnectServiceClient : System.ServiceModel.ClientBase<Parker.Sandbox.AMSConnect.IMASCAMSConnectService>, Parker.Sandbox.AMSConnect.IMASCAMSConnectService {
        
        public MASCAMSConnectServiceClient() {
        }
        
        public MASCAMSConnectServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MASCAMSConnectServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MASCAMSConnectServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MASCAMSConnectServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void CityConnectSignUp(Parker.Sandbox.AMSConnect.CityConnectSignupViewModel model) {
            base.Channel.CityConnectSignUp(model);
        }
        
        public System.Threading.Tasks.Task CityConnectSignUpAsync(Parker.Sandbox.AMSConnect.CityConnectSignupViewModel model) {
            return base.Channel.CityConnectSignUpAsync(model);
        }
        
        public Parker.Sandbox.AMSConnect.IndividualViewModel CreateIndividual() {
            return base.Channel.CreateIndividual();
        }
        
        public System.Threading.Tasks.Task<Parker.Sandbox.AMSConnect.IndividualViewModel> CreateIndividualAsync() {
            return base.Channel.CreateIndividualAsync();
        }
        
        public Parker.Sandbox.AMSConnect.IndividualViewModel[] Search() {
            return base.Channel.Search();
        }
        
        public System.Threading.Tasks.Task<Parker.Sandbox.AMSConnect.IndividualViewModel[]> SearchAsync() {
            return base.Channel.SearchAsync();
        }
    }
}
